### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by DenisBiondic** [TimeXt/FluentTimeSpan-CSharp#2]
For utility libraries such as this one, dependency on .NET Core or .NET Framework reduced the target use cases too much, therefore .NET Standard is the recommended way for 99% of libraries out there... Should be possible, there should be no use cases which are not supported by .NET Standard 2.0, or even some lower versions.

**Comment by GuepardoApps** [comment]
The reason why i switched to .NET Core was this: 
https://docs.microsoft.com/en-us/dotnet/api/system.timespan.op_division?view=netcore-2.1
TimeSpan division seems not to be  available in .NET Standard
But... I don't use the feature..., so yeah 😆 i will switch back to standard 👍

**Comment by GuepardoApps** [comment]
Back to .Net Standard 2.0 with this [Commit](https://github.com/TimeXt/FluentTimeSpan-CSharp/commit/7a27cf76cf1aab014319ea4719969a7fecc30675)

**Comment by julealgon** [comment]
@JonasSchubert , have you considered multi-targeting your library? It is currently only exposed as Net Standard 2.1, which cannot be referenced by .Net 4.8 projects or earlier .Net Core ones.

Where exactly is the .Net Standard 2.1-specific Division operator used? Would it be possible to provide reduced functionality without it instead?

**Comment by JonasSchubert** [comment]
@julealgon Indeed there is no need for .Net Standard 2.1. I set it back to .Net Standard 2.0 in the current version 0.6.0.

**Comment by julealgon** [comment]
Thank you for looking into this @JonasSchubert , much appreciated.
